name: Clone gecko-dev
on:
  workflow_dispatch:
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Install Mercurial
        run: |
          sudo apt update
          sudo apt install mercurial
      - name: Clone gecko-dev
        uses: actions/checkout@v3
        with:
          repository: mozilla/gecko-dev
          path: gecko-dev
